// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUG3gXLvdC9V55iOdl_wvDKAdDX88-jOQ',
    appId: '1:710120338502:web:be309e0d59ee4daf594647',
    messagingSenderId: '710120338502',
    projectId: 'plotsklapps-dev',
    authDomain: 'plotsklapps-dev.firebaseapp.com',
    storageBucket: 'plotsklapps-dev.firebasestorage.app',
    measurementId: 'G-ZH85ZCZ12P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOAZCRnpJ9P0bfTd_wEovTyeO4-j5WjBo',
    appId: '1:710120338502:android:93704a8e6fdfa2d7594647',
    messagingSenderId: '710120338502',
    projectId: 'plotsklapps-dev',
    storageBucket: 'plotsklapps-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwnIpFoT5ij9Gz4ECe3XD0mX6TJysFVF0',
    appId: '1:710120338502:ios:3936fbeeaad887ea594647',
    messagingSenderId: '710120338502',
    projectId: 'plotsklapps-dev',
    storageBucket: 'plotsklapps-dev.firebasestorage.app',
    iosBundleId: 'dev.plotsklapps.plotsfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwnIpFoT5ij9Gz4ECe3XD0mX6TJysFVF0',
    appId: '1:710120338502:ios:3936fbeeaad887ea594647',
    messagingSenderId: '710120338502',
    projectId: 'plotsklapps-dev',
    storageBucket: 'plotsklapps-dev.firebasestorage.app',
    iosBundleId: 'dev.plotsklapps.plotsfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUG3gXLvdC9V55iOdl_wvDKAdDX88-jOQ',
    appId: '1:710120338502:web:be309e0d59ee4daf594647',
    messagingSenderId: '710120338502',
    projectId: 'plotsklapps-dev',
    authDomain: 'plotsklapps-dev.firebaseapp.com',
    storageBucket: 'plotsklapps-dev.firebasestorage.app',
    measurementId: 'G-ZH85ZCZ12P',
  );

}